Repository leekelleher/umbraco-contentment, pull requests merged in 2022-10, with the labels that each got.

#262 Update render-macro.md Documentation
  docs/editors/render-macro.md
Labels: documentation, hacktoberfest-accepted

#264 Add docs for the Content by XPath data-source
  docs/data-sources/data-source--umbraco-content-xpath--configuration-editor.png
  docs/data-sources/data-source--umbraco-content-xpath.md
Labels: documentation, hacktoberfest-accepted

#265 Add docs for the Umbraco Content data-source
  docs/data-sources/data-source--umbraco-content--configuration-editor-01.png
  docs/data-sources/data-source--umbraco-content--configuration-editor-02.png
  docs/data-sources/data-source--umbraco-content.md
Labels: documentation, hacktoberfest-accepted

#266 Umbraco content context as a service
  docs/editors/data-list.md
  src/Umbraco.Community.Contentment/Composing/ContentmentComposer.cs
  src/Umbraco.Community.Contentment/Polyfill/Web/UmbracoContextAccessorExtensions.cs
  src/Umbraco.Community.Contentment/Services/ContentmentContentContext.cs
  src/Umbraco.Community.Contentment/Services/IContentmentContentContext.cs
Labels: feature-request, hacktoberfest-accepted

#267 Umbraco content context as a service - Breaking changes
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/ExamineDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentXPathDataListSource.cs
Labels: feature-request, hacktoberfest-accepted

#269 Added Swedish translations for backoffice
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/sv.xml
Labels: feature-request, hacktoberfest-accepted

#270 Added Dutch translations for backoffice
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/nl.xml
Labels: feature-request, hacktoberfest-accepted

#271 Adding French translations
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/fr.xml
Labels: feature-request, hacktoberfest-accepted

#272 Preparing v4.2.0 release
  .github/README.md
  .github/ROADMAP.md
  VERSION
  build/build-pkgs.ps1
  docs/data-sources/data-source--umbraco-content--configuration-editor-01.png
  docs/data-sources/data-source--umbraco-content--configuration-editor-02.png
  docs/data-sources/data-source--umbraco-content-xpath--configuration-editor.png
  docs/data-sources/data-source--umbraco-content-xpath.md
  docs/data-sources/data-source--umbraco-content.md
  docs/editors/data-list.md
  docs/editors/render-macro.md
  src/Umbraco.Community.Contentment/Composing/ContentmentComposer.cs
  src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/ContentBlock.cs
  src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/ContentBlocksExtensions.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataListApiController.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/ExamineDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentXPathDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/ItemPicker/item-picker.overlay.html
  src/Umbraco.Community.Contentment/Polyfill/Web/UmbracoContextAccessorExtensions.cs
  src/Umbraco.Community.Contentment/Services/ContentmentContentContext.cs
  src/Umbraco.Community.Contentment/Services/ContentmentContentContextExtensions.cs
  src/Umbraco.Community.Contentment/Services/IContentmentContentContext.cs
  src/Umbraco.Community.Contentment/Umbraco.Community.Contentment.csproj
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/es.xml
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/fr.xml
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/nl.xml
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/sv.xml
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/package.manifest
Labels: release

#273 Added missing translations for Danish
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/da.xml
Labels: feature-request, hacktoberfest-accepted

#274 Added `Group` property to `TimeZoneDataSource` example
  docs/editors/data-list.md
Labels: documentation, hacktoberfest-accepted

#276 Umbraco Languages Preview Image
  docs/data-sources/data-source--umbraco-languages--configuration-editor-01.png
  docs/data-sources/data-source--umbraco-languages.md
Labels: documentation, hacktoberfest-accepted

#275 Umbraco Users Data Source Preview
  docs/data-sources/data-source--umbraco-users--configuration-editor-01.png
  docs/data-sources/data-source--umbraco-users--configuration-editor-02.png
  docs/data-sources/data-source--umbraco-users--configuration-editor-03.png
  docs/data-sources/data-source--umbraco-users--configuration-editor-04.png
  docs/data-sources/data-source--umbraco-users.md
Labels: documentation, hacktoberfest-accepted

#277 Update pt-br translation
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/Lang/pt-br.xml
Labels: feature-request, hacktoberfest-accepted, bug-fix

#280 Removes `sealed` modifier from `DataListItem` class
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataListItem.cs
Labels: feature-request, hacktoberfest-accepted

#284 Adds docs for .NET Enumeration, Examine Query, Umbraco Content Proper…
  docs/data-sources/data-source--enum.md
  docs/data-sources/data-source--enum.png
  docs/data-sources/data-source--examine.md
  docs/data-sources/data-source--examine.png
  docs/data-sources/data-source--umbraco-content-properties.md
  docs/data-sources/data-source--umbraco-content-properties.png
  docs/data-sources/data-source--umbraco-content-types.md
  docs/data-sources/data-source--umbraco-content-types.png
Labels: documentation, hacktoberfest-accepted
