Repository leekelleher/umbraco-contentment, pull requests merged in 2023-10, with the labels that each got.

#347 Content Blocks - Remove items from value that cannot be selected
  src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/content-blocks.js
Labels: feature-request, hacktoberfest-accepted

#348 Added `id` property to `package.manifest` file
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/package.manifest
Labels: feature-request, hacktoberfest-accepted

#350 Update CopyContentmentPackageAssets target to run BeforeBuild
  build/_nuget-post-install.targets
  build/_vs-copy-assets.targets
Labels: hacktoberfest-accepted, bug-fix

#351 Social Links - added Discord icon
  src/Umbraco.Community.Contentment/DataEditors/SocialLinks/SocialLinksConfigurationEditor.cs
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/backoffice/icons/icon-discord.svg
Labels: feature

#354 twitterLogo Update in Social Links
  src/Umbraco.Community.Contentment/DataEditors/SocialLinks/SocialLinksConfigurationEditor.cs
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/backoffice/icons/icon-x-twitter.svg
Labels: feature-request

#355 Include ability to sort content alphabetically in umbraco content data list source
  src/Umbraco.Cms.10.x/uSync/v10/DataTypes/ContentmentDataListUmbracoContent.config
  src/Umbraco.Cms.10.x/uSync/v10/DataTypes/ContentmentDataPickerUmbracoContent.config
  src/Umbraco.Cms.12.x/uSync/v9/DataTypes/ContentmentDataListUmbracoContent.config
  src/Umbraco.Cms.12.x/uSync/v9/DataTypes/ContentmentDataPickerUmbracoContent.config
  src/Umbraco.Cms.8.x/uSync/v8/DataTypes/ContentmentDataListUmbracoContent.config
  src/Umbraco.Cms.8.x/uSync/v8/DataTypes/ContentmentDataPickerUmbracoContent.config
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentDataListSource.cs
Labels: hacktoberfest-accepted, feature

#356 Data List - SQL data-source - refactored and separated out
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/SqlDataListSource.NET472.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/SqlDataListSource.NET5_0.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/SqlDataListSource.NET6_0.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/SqlDataListSource.cs
Labels: bug-report, feature

#360 .NET 6 Documentation added
  .github/README.md
Labels: documentation, hacktoberfest-accepted
