Repository leekelleher/umbraco-contentment, pull requests merged in 2023-05, with the labels that each got.

#317 Preparing v4.4.3 release
  .github/README.md
  VERSION
  src/Umbraco.Community.Contentment.sln
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataListValueConverter.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentPropertyValueDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentXPathDataListSource.cs
  src/Umbraco.Community.Contentment/Services/ContentmentContentContextExtensions.cs
  src/Umbraco.Community.Contentment/Umbraco.Community.Contentment.csproj
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/package.manifest
  umbraco-marketplace.json
Labels: release

#321 Adds info about DataListItem attribute
  docs/data-sources/data-source--enum.md
Labels: documentation

#320 Added Translation Dictionary support to UmbracoContentTypesDataListSource
  src/Umbraco.Community.Contentment/Core/Services/LocalizedTextServiceExtensions.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentTypesDataListSource.cs
  src/Umbraco.Community.Contentment/Polyfill/Core/Services/LocalizedTextServiceExtensions.cs
Labels: feature-request, ignored-template

#326 Fixes #325 Added description to button title
  src/Umbraco.Community.Contentment/DataEditors/Buttons/buttons.html
Labels: feature-request
