Repository leekelleher/umbraco-contentment, pull requests merged in 2024-12, with the labels that each got.

#426 Data List: Adds "contentment.update.value" event to List Editors
  src/Umbraco.Community.Contentment/DataEditors/Buttons/buttons.js
  src/Umbraco.Community.Contentment/DataEditors/CheckboxList/checkbox-list.js
  src/Umbraco.Community.Contentment/DataEditors/DropdownList/dropdown-list.js
  src/Umbraco.Community.Contentment/DataEditors/ItemPicker/item-picker.js
  src/Umbraco.Community.Contentment/DataEditors/RadioButtonList/radio-button-list.js
  src/Umbraco.Community.Contentment/DataEditors/Tags/tags.js
  src/Umbraco.Community.Contentment/DataEditors/TemplatedList/templated-list.js
Labels: type/feature

#428 Data List/Picker: Adds data-source support for Delivery API
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataListValueConverter.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentTypesDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentXPathDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoMembersDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoUserGroupDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoUsersDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataPicker/DataPickerValueConverter.cs
  src/Umbraco.Community.Contentment/DataEditors/_/DataSources/IDataSourceDeliveryApiValueConverter.cs
Labels: type/feature

#429 Data Picker: Adds support for non-integer IDs
  src/Umbraco.Community.Contentment/DataEditors/DataPicker/DataPickerApiController.cs
  src/Umbraco.Community.Contentment/DataEditors/DataPicker/data-picker.js
Labels: type/feature

#430 Examine data-source: Adds native support for Data Picker
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/ExamineDataListSource.cs
Labels: type/feature, type/bug-fix

#431 Preparing v5.1.0 release
  .github/README.md
  .github/ROADMAP.md
  VERSION
  src/Umbraco.Cms.13.x/Umbraco.Cms.13.x.csproj
  src/Umbraco.Cms.13.x/appsettings-schema.usync.json
  src/Umbraco.Community.Contentment.sln
  src/Umbraco.Community.Contentment.sln.licenseheader
  src/Umbraco.Community.Contentment/DataEditors/Buttons/buttons.js
  src/Umbraco.Community.Contentment/DataEditors/CheckboxList/checkbox-list.js
  src/Umbraco.Community.Contentment/DataEditors/ConfigurationEditor/configuration-editor.js
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataListValueConverter.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/ExamineDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentTypesDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentXPathDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoMembersDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoUserGroupDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoUsersDataListSource.cs
  src/Umbraco.Community.Contentment/DataEditors/DataList/data-list.editor.js
  src/Umbraco.Community.Contentment/DataEditors/DataPicker/DataPickerApiController.cs
  src/Umbraco.Community.Contentment/DataEditors/DataPicker/DataPickerValueConverter.cs
  src/Umbraco.Community.Contentment/DataEditors/DataPicker/data-picker.js
  src/Umbraco.Community.Contentment/DataEditors/DataTable/data-table.js
  src/Umbraco.Community.Contentment/DataEditors/DropdownList/dropdown-list.js
  src/Umbraco.Community.Contentment/DataEditors/ItemPicker/item-picker.js
  src/Umbraco.Community.Contentment/DataEditors/MacroPicker/macro-picker.js
  src/Umbraco.Community.Contentment/DataEditors/Notes/notes.html
  src/Umbraco.Community.Contentment/DataEditors/RadioButtonList/radio-button-list.js
  src/Umbraco.Community.Contentment/DataEditors/SocialLinks/social-links.js
  src/Umbraco.Community.Contentment/DataEditors/Tags/tags.js
  src/Umbraco.Community.Contentment/DataEditors/TemplatedList/templated-list.js
  src/Umbraco.Community.Contentment/DataEditors/_/DataSources/IDataSourceDeliveryApiValueConverter.cs
  src/Umbraco.Community.Contentment/Umbraco.Community.Contentment.csproj
  src/Umbraco.Community.Contentment/gulpfile.js
Labels: release

#436 Data List: Buttons: Enable deselection of single buttons
  src/Umbraco.Community.Contentment/DataEditors/Buttons/buttons.js
  src/Umbraco.Community.Contentment/DataEditors/TemplatedList/templated-list.js
Labels: type/feature-request, affected/v5

#438 Content Blocks: Sets `key` of copied blocks
  src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/content-blocks.js
  src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/content-blocks.overlay.js
Labels: type/bug-fix

#437 V6: Data List: Buttons: Enables deselection of single button
  src/Umbraco.Community.Contentment.Client/src/property-editor-ui/buttons/buttons.element.ts
  src/Umbraco.Community.Contentment.Client/src/property-editor-ui/templated-list/templated-list.element.ts
Labels: type/feature-request, affected/v6
