Repository leekelleher/umbraco-contentment, pull requests merged in 2024-03, with the labels that each got.

#385 Preparing v4.6.1 release
  VERSION
  src/Umbraco.Cms.13.x/uSync/v9/MediaTypes/umbracomediaarticle.config
  src/Umbraco.Cms.13.x/uSync/v9/MemberTypes/member.config
  src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/content-blocks.js
  src/Umbraco.Community.Contentment/DataEditors/EditorNotes/EditorNotesConfigurationConnector.cs
  src/Umbraco.Community.Contentment/DataEditors/Notes/NotesConfigurationConnector.cs
  src/Umbraco.Community.Contentment/DataEditors/RenderMacro/RenderMacroConfigurationConnector.cs
  src/Umbraco.Community.Contentment/Polyfill/Core/Deploy/IContextCache.cs
  src/Umbraco.Community.Contentment/Polyfill/Core/Deploy/ImageSourceParserExtensions.cs
  src/Umbraco.Community.Contentment/Polyfill/Core/Deploy/LocalLinkParserExtensions.cs
  src/Umbraco.Community.Contentment/Polyfill/Core/Deploy/MacroParserExtensions.cs
  src/Umbraco.Community.Contentment/Polyfill/Core/Deploy/PassThroughCache.cs
  src/Umbraco.Community.Contentment/Umbraco.Community.Contentment.csproj
  src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/package.manifest
  umbraco-marketplace.json
Labels: release

#382 Fix: Umbraco 13.2.0 - DataType Configuration performance improvement
  .gitignore
  src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/ContentBlocksDataEditor.cs
  src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/ContentBlocksDataValueEditor.cs
Labels: feature-request

#386 DataList: Umbraco Content: Adds Dynamic Root support
  src/Umbraco.Community.Contentment/DataEditors/ContentPicker/content-source.html
  src/Umbraco.Community.Contentment/DataEditors/ContentPicker/content-source.js
  src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentDataListSource.cs
Labels: feature
